stepchowfun/poi

cli/main.cpp, include/ast.h, include/optimizer.h, include/token.h, include/value.h, src/ast.cpp, src/optimizer.cpp, src/parser.cpp, src/value.cpp
Implement the interpreter.
**Fixes:** N/A
=> Implement the interpreter

include/ast.h, include/token.h, src/ast.cpp, src/parser.cpp, src/tokenizer.cpp
Add support for parsing member accesses.
**Fixes:** N/A
=> Add support for parsing member accesses

CONTRIBUTING.md, cli/main.cpp, include/ast.h, include/error.h, include/parser.h, include/string_pool.h, include/token.h, include/tokenizer.h, include/value.h, src/ast.cpp, src/optimizer.cpp, src/parser.cpp, src/string_pool.cpp, src/token.cpp, src/tokenizer.cpp, src/value.cpp
Implement preliminary support for ADT values and string pooling.
**Fixes:** N/A
=> Implement preliminary support for ADT values and string pooling

README.md
=> Fix tree example in README

README.md
=> Use full words for tree example

src/parser.cpp
Simplify the parser by removing the `top_level` flag. We used to have this flag because `Group`s were sequences of statements, and the "top level" `Group` was a special case: the whole program didn't need to be surrounded in parentheses, unlike regular `Group`s.
Now that `Group`s only contain a single term in their body, we don't need to parse the whole program as a `Group`. We now parse it as a `Term` and get rid of this special case.
**Fixes:** N/A
=> Simplify the parser by removing the `top_level` flag

src/parser.cpp
Fix a couple error messages.
**Fixes:** N/A
=> Fix a couple error messages

Makefile, scripts/check-line-lengths.sh, scripts/check-whitespace.sh
Add a script to check for various style issues related to whitespace
**Fixes:** N/A
=> Add a script to check for various style issues related to whitespace

src/parser.cpp
Tweak a couple error messages.
**Fixes:** N/A
=> Tweak a couple error messages

cli/main.cpp
Change the CLI to print errors to `STDERR` instead of `STDOUT`.
**Fixes:** N/A
=> Change the CLI to print errors to STDERR instead of STDOUT

.travis.yml, CONTRIBUTING.md, Makefile, scripts/run-tests.rb, tests/id.json
Introduce a simple testing framework. Each test is specified in a JSON file in the `tests/` directory. The tests can be run with `./test.rb test TEST_NAME` or just `./test.rb test` to run all the tests.
**Fixes:** N/A
=> Introduce a simple testing framework

README.md
Update the examples in `README.md`.
**Fixes:** N/A
=> Update the examples in README.md

include/ast.h, src/ast.cpp
Add `const` to all the `eval` methods.
**Fixes:** N/A
=> Add const to all the eval methods

tests/nested_member.json
Add a test for nested member accesses.
**Fixes:** N/A
=> Add a test for nested member accesses

include/ast.h, include/token.h, src/ast.cpp, src/parser.cpp, src/tokenizer.cpp
Implement pattern parsing. Based on https://github.com/stepchowfun/poi/pull/16.
**Fixes:** N/A
=> Implement pattern parsing

include/ast.h, src/ast.cpp, src/parser.cpp
=> Implement pattern matching for let and abstraction

tests/abstraction_pattern.json, tests/let_pattern.json
=> Add tests for pattern matching

README.md
Add some pattern matching examples to `README.md`.
**Fixes:** N/A
=> Add some pattern matching examples to README.md

README.md
Demonstrate nested pattern matching in `README.md`.
**Fixes:** N/A
=> Demonstrate nested pattern matching in README.md

tests/match_error.json
=> Add a failing test for pattern matching

src/parser.cpp, tests/duplicate_variable_in_pattern.json
Add error checking for duplicate variables in patterns. I also added a test for this case.
**Fixes:** N/A
=> Add error checking for duplicate variables in patterns

src/parser.cpp, tests/duplicate_constructor.json
=> Enforce unique constructor names for a data type

include/token.h, src/parser.cpp, src/tokenizer.cpp
Rename `BRACE` to `CURLY`.
**Fixes:** N/A
=> Rename `BRACE` to `CURLY`

src/ast.cpp
Enforce that patterns refer to actual constructors for the appropriate type.
Previously, this would work:
```
bool = data {true, false}
match bool.true {
{invalid} -> bool.true
}
```
Now it results in an error:
```
Error: 'invalid' is not a constructor of data {true, false}.
Location: example.poi @ 3:3 - 3:11
{invalid} -> bool.true
^^^^^^^^^
```
**Fixes:** N/A
=> Enforce that patterns refer to actual constructors for the appropriate type

src/parser.cpp
Add a missing case to the grammar.
**Fixes:** N/A
=> Add a missing case to the grammar

src/ast.cpp
Fix a couple issues with pattern matching.
**Fixes:** N/A
=> Fix a couple issues with pattern matching

src/ast.cpp
Instead of evaluating the matched case as a function value, directly evaluate the body of the abstraction. This is faster, since we don't need the closure created by evaluating the abstraction.
**Fixes:** N/A
=> Simplify eval for Match

src/ast.cpp
Introduce a minimum depth for tail call elimination to produce better stack traces.
Example:
```
bool = {true, false}
not = x -> match x {
}
option = {none, some value}
map = f -> x -> match x {
{none} -> option.none
{some value} -> option.some (f value)
}
(x -> x) (map not (option.some option.none))
```
Before:
```
Error: 'true' is not a constructor of {none, some value}.
example.poi @ 2:12 - 5:1
example.poi @ 10:19 - 10:39
example.poi @ 13:1 - 13:44
```
After:
```
Error: 'true' is not a constructor of {none, some value}.
example.poi @ 2:12 - 5:1
example.poi @ 10:31 - 10:39
example.poi @ 10:19 - 10:39
example.poi @ 8:17 - 11:1
example.poi @ 13:10 - 13:44
example.poi @ 13:1 - 13:44
example.poi @ 8:1 - 13:44
example.poi @ 7:1 - 13:44
example.poi @ …
```
=> Introduce a minimum depth for tail call elimination to produce better stack traces

src/parser.cpp
Optimize the parser and ensure that it takes linear time in the worst case.
**Fixes:** N/A
=> Optimize the parser and ensure that it takes linear time in the worst case

src/parser.cpp
Remove an unnecessary throw.
**Fixes:** N/A
=> Remove an unnecessary throw

cli/main.cpp, include/optimizer.h, src/optimizer.cpp
Add the skeleton of an optimizer. We can put the register allocation code in here.
**Fixes:** N/A
=> Add the skeleton of an optimizer

include/bytecode.h, include/ir.h, src/ast.cpp, src/interpreter.cpp, src/ir.cpp, src/optimizer.cpp
Define a type alias for registers so we can easily try different sizes.
**Fixes:** N/A
=> Define a type alias for registers so we can easily try different sizes
