stepchowfun/poi

README.md
include/ast.h
include/token.h
src/ast.cpp
src/parser.cpp
src/tokenizer.cpp

Add support for parsing ADTs. Examples:
bool = data (true, false)
maybe = data (none, just x)
tree = data (
empty
left x
right x
)
tree
These examples are parsed as:
(bool = data (true, false), (maybe = data (none, just x), (tree = data (empty, left x, right x), tree)))
**Fixes:** N/A

Add support for parsing ADTs

---

include/ast.h
include/value.h
src/ast.cpp
src/value.cpp

Make data types first-class values. Now the following successfully runs:
bool = data (true, false)
(x -> x) bool
It evaluates to `data (true, false)`. But what what happens if we try this:
bool = data (true, false)
bool (x -> x)
We get the following error:
Error: data (true, false) is not a function.
test.poi @ 3:1 - 3:13
bool (x -> x)
^^^^^^^^^^^^^
Dynamic type checking!
**Fixes:** N/A

Make data types first-class values

---

README.md
include/ast.h
include/value.h
src/ast.cpp
src/optimizer.cpp
src/parser.cpp
src/tokenizer.cpp
src/value.cpp

Add support for constructing ADTs. The following examples are now supported:
maybe = data (none, just x)
id = x -> x
maybe.just id
bool = data (true, false)
true = bool.true
false = bool.false
true
maybe = data (none, just x)
id = x -> x
maybe.just id id
**Fixes:** N/A

Add support for constructing ADTs

---

scripts/install.sh

I tried to run the install command in Ubuntu:
$ curl -sSf https://raw.githubusercontent.com/stepchowfun/poi/master/scripts/install.sh | sh
sh: 2: set: Illegal option -o pipefail
This error happens because Ubuntu's default shell is dash, not bash, and dash doesn't support the `pipefail` option. The install script had a [shebang](https://en.wikipedia.org/wiki/Shebang_\(Unix\)) to specify that it should be run with bash, but apparently this is ignored when piping the script into dash.
This PR makes the install script more portable by removing the bash-specific options. The other two scripts are not intended to be piped into a shell, so we can assume their shebangs work (and I confirmed that this is the case for Ubuntu).
**Fixes:** N/A

Make the install script more portable

---

README.md
include/ast.h
src/ast.cpp

Implement record field access. Now algebraic data types can be used like records. For example, the following is now supported:
bool = data (true, false)
maybe = data (none, just value)
something = maybe.just bool.true
something.value
Another example:
bool = data (true, false)
config = data (new fooEnabled barEnabled)
c = config.new bool.true bool.false
c.barEnabled
**Fixes:** N/A

Implement record field access

---

src/parser.cpp

Simplify the parser by unifying `MEMO_KEY_GENERAL` and `MEMO_KEY_SIMPLE`.
It used to be that `MEMO_KEY_GENERAL` had 4 arguments whereas `MEMO_KEY_SIMPLE` had 2. Now it's 3 and 2—not enough of a difference to warrant the existence of the `MEMO_KEY_SIMPLE` helper.
**Fixes:** N/A

Simplify the parser by unifying MEMO_KEY_GENERAL and MEMO_KEY_SIMPLE

---

include/ast.h
src/ast.cpp
src/parser.cpp

Introduce `Node`, which is a superclass of `Term`. In the future, we will have AST nodes that are not terms (e.g., `Pattern`), which we still want to memoize.
**Fixes:** N/A

Introduce Node

---

include/ast.h

Remove a redundant method declaration. Good catch @ewang12.
**Fixes:** N/A

Remove a redundant method declaration

---

CONTRIBUTING.md
cli/main.cpp
include/ast.h
include/error.h
include/parser.h
include/string_pool.h
include/token.h
include/tokenizer.h
include/value.h
include/version.h
scripts/version.sh
src/ast.cpp
src/error.cpp
src/parser.cpp
src/string_pool.cpp
src/token.cpp
src/tokenizer.cpp
src/value.cpp

Introduce a new error handling mechanism for the parser. This PR also contains many other improvements, especially:
- The namespace `poi` was renamed to `Poi`.
- `const` was added where appropriate, and the C++ style guide was amended to reflect this new style.
**Fixes:** N/A

Introduce a new error handling mechanism for the parser

---

src/parser.cpp
tests/duplicate_constructor.json
tests/duplicate_parameter_in_constructor.json

Add error checking for duplicate parameters in data constructors. I also added a new test, simplified an existing test, fixed a bug in some existing error handling, and made some other existing error handling more robust.
**Fixes:** N/A

Add error checking for duplicate parameters in data constructors

---

README.md
include/ast.h
include/token.h
src/ast.cpp
src/parser.cpp
src/token.cpp
src/tokenizer.cpp
tests/abstraction_pattern.json
tests/bool.json
tests/constructor_function.json
tests/constructor_value.json
tests/duplicate_constructor.json
tests/duplicate_parameter_in_constructor.json
tests/let_pattern.json
tests/map.json
tests/match.json
tests/match_error.json
tests/maybe.json
tests/member.json
tests/nested_member.json
tests/tree.json
tests/type_error.json
tests/unit.json
tests/void.json

Implement the `match` construct and update the syntax to use curly braces where appropriate. I fixed all the existing tests (changing parens to curly braces where appropriate) and added a couple new tests for `match`.
Now we can do the following:
```
bool = data {true, false}
not = x -> match x {
}
option = data {none, some value}
map = f -> x -> match x {
{none} -> option.none
{some value} -> option.some (f value)
}
map not (option.some bool.false)
```
**Fixes:** N/A

Implement `match` and update the syntax to use curly braces where appropriate

---

README.md
include/ast.h
include/value.h
src/ast.cpp
src/parser.cpp
src/value.cpp

Rename `Abstraction` -> `Function` and `Let` -> `Definition`.
**Fixes:** N/A

Rename Abstraction -> Function and Let -> Definition

---

include/util.h
include/value.h
src/ast.cpp
src/parser.cpp
src/util.cpp
src/value.cpp
tests/nat.json

Implement let recursion. Now we can do this:
```
nat = data {zero, succ n}
add = x -> y -> match x {
{zero} -> y
{succ n} -> nat.succ (add n y)
}
two = nat.succ (nat.succ nat.zero)
three = nat.succ (nat.succ (nat.succ nat.zero))
add two three
```
This is what happens if we try to do a recursive reference outside of a function:
```
x = x
x
Error: Recursive references must occur in function bodies.
Location: example.poi @ 1:5
x = x
^
```
**Fixes:** N/A

Implement let recursion

---

include/ast.h
include/error.h
include/parser.h
include/string_pool.h
include/token.h
include/tokenizer.h
include/util.h
include/value.h
include/version.h
src/ast.cpp
src/parser.cpp

Remove extra line breaks surrounding namespace bodies. What do you think about this?
I think it looked weird to have this at the end of every file:
```
};
};
}
```
With this change, we would have:
```
};
};
}
```
**Fixes:** N/A

Remove extra line breaks surrounding namespace bodies

---

src/parser.cpp

Fix a bug regarding the free variables of a binding expression. Thanks @ewang12 for discovering this example which triggers the bug:
```
f = x -> \
g = f
g
f (x -> x)
```
**Fixes:** N/A

Fix a bug regarding the free variables of a binding expression

---

include/value.h
src/ast.cpp
src/value.cpp

Instead of storing a pointer to a DataTypeValue in a DataValue, we could store a pointer to a DataType. This makes it slightly more efficient to use a DataValue. I also deleted an unused variable.
**Fixes:** N/A

Store DataTypes in DataValues

---

include/ast.h
src/ast.cpp

I think AST nodes should never refer to values. It would be nice if the AST were a static thing that comes from parsing the program and not running it (so we only have to garbage collect values). This PR brings us closer to that.
**Fixes:** N/A

Do not have AST nodes store pointers to values

---

include/ast.h
include/value.h
src/ast.cpp
src/parser.cpp

Construct AST nodes for constructor functions statically. Now, all `Node`s are constructed statically and only `Value`s are constructed dynamically. This not only improves performance but also simplifies reasoning about garbage collection.
**Fixes:** N/A

Construct AST nodes for constructor functions statically

---

cli/main.cpp
include/ast.h
include/parser.h
include/token.h
include/util.h
include/value.h
src/ast.cpp
src/parser.cpp
src/token.cpp
src/util.cpp
src/value.cpp

Previously, only the outside of every type was declared `const`. For example:
```c++
const std::shared_ptr<std::unordered_set<size_t>> free_variables;
```
This PR adds `const` to all the "inner" types. So the above becomes:
```c++
const std::shared_ptr<const std::unordered_set<size_t>> free_variables;
```
Note that we do not need to add `const` to `size_t` in this example, because `const` on the container type implies `const` on the members (attempting to mutate a member will raise a compiler error). In some cases, we cannot even add an explicit `const` to the member type, because the implementation of the container must be able to move elements around internally (e.g., to resize a vector).
**Fixes:** N/A

Make everything const-correct

---

include/value.h

Remove some unnecessary forward declarations in `value.h`.
We have a situation where `value.h` and `ast.h` depend on each other. To resolve this, we had neither `include` the other, and used forward references to achieve the mutual dependency. But this is only necessary in one direction. After this PR, `value.h` `include`s `ast.h`, but not the other way around. Only `ast.h` needs a forward declaration.
**Fixes:** N/A

Remove some unnecessary forward declarations

---

README.md
include/token.h
src/ast.cpp
src/parser.cpp
src/tokenizer.cpp
tests/abstraction_pattern.json
tests/bool.json
tests/constructor_function.json
tests/constructor_value.json
tests/duplicate_constructor.json
tests/duplicate_parameter_in_constructor.json
tests/let_pattern.json
tests/map.json
tests/match.json
tests/match_error.json
tests/maybe.json
tests/member.json
tests/nat.json
tests/nested_member.json
tests/tree.json
tests/type_error.json
tests/unit.json
tests/void.json

Remove the unnecessary `data` keyword. The grammar is still unambiguous without it. Now we can write:
```
bool = {true, false}
```
That's probably about as minimal as we can get. 😄 
**Fixes:** N/A

Remove the unnecessary 'data' keyword

---

src/parser.cpp

Fix the grammar for match expressions. There were two problems:
1. In the grammar, we have a `SEPARATOR` between the discriminee and the cases. The parser does not expect any `SEPARATOR` there. So I removed it from the grammar.
2. Removing the `SEPARATOR` actually revealed an ambiguity in the grammar:
```
Found a sentential form with two different derivations:
MATCH Variable LEFT_CURLY RIGHT_CURLY LEFT_CURLY RIGHT_CURLY
Derivation 1:
0: Term
1: Match
2: MATCH Term LEFT_CURLY CaseList RIGHT_CURLY
3: MATCH Application LEFT_CURLY CaseList RIGHT_CURLY
4: MATCH Term1 Term2 LEFT_CURLY CaseList RIGHT_CURLY
5: MATCH Variable Term2 LEFT_CURLY CaseList RIGHT_CURLY
6: MATCH Variable DataType LEFT_CURLY CaseList RIGHT_CURLY
7: MATCH Variable LEFT_CURLY DataConstructorList RIGHT_CURLY LEFT_CURLY …
```

Fix the grammar for match expressions

---

include/ast.h
include/value.h
src/ast.cpp
src/parser.cpp
src/value.cpp

Previously, we would construct a `Value` for a constructor whenever it was referenced. Now we preallocate all of the constructors when the type is created.
Before:
```
option = {none, some value} # Constructors don't exist as values yet
option.some # Function created here
```
After:
```
option = {none, some value} # Both constructors created here
option.some # Function already exists, just return it
```
**Fixes:** N/A

Optimize constructor references by precomputing them

---

cli/main.cpp
include/ast.h
include/value.h
src/ast.cpp
src/value.cpp

Implement tail call optimization using the trampoline technique.
Now infinite tail calls actually cause the program to loop forever rather than segfault:
```
f = x -> f x
f (y -> y)
```
Also, we now have a maximum recursion depth for non-tail calls:
```
f = x -> (y -> y) (f x)
f (z -> z)
```
**Fixes:** N/A

Implement tail call optimization

---

cli/main.cpp
include/ast.h
include/error.h
include/parser.h
include/token.h
include/tokenizer.h
include/value.h
src/ast.cpp
src/error.cpp
src/parser.cpp
src/string_pool.cpp
src/value.cpp

Show stack traces when an evaluation error happens. Some differences between Poi's stack traces and those of other programming languages:
- Poi does tail call elimination, which means those stack frames disappear. That makes stack traces less useful in general, sadly.
- Poi's stack traces include a separate frame for every AST node currently being evaluated (except those in tail position, as noted above), rather than just the distinct lines.
- For each frame, Poi provides not only the relevant line numbers but also the relevant column numbers.
Example program:
```
bool = {true, false}
not = x -> match x {
}
option = {none, some value}
map = f -> x -> match x {
{none} -> option.none
{some value} -> option.some (f value)
}
(x -> x) (map not …
```

Show stack traces when an evaluation error happens

---

src/ast.cpp

Hide frames corresponding to `Binding` expressions from stack traces.
Example:
```
bool = {true, false}
not = x -> match x {
}
option = {none, some value}
map = f -> x -> match x {
{none} -> option.none
{some value} -> option.some (f value)
}
(x -> x) (map not (option.some option.none))
```
Before:
```
Error: 'true' is not a constructor of {none, some value}.
example.poi @ 2:12 - 5:1
example.poi @ 10:31 - 10:39
example.poi @ 10:19 - 10:39
example.poi @ 8:17 - 11:1
example.poi @ 13:10 - 13:44
example.poi @ 13:1 - 13:44
example.poi @ 8:1 - 13:44
example.poi @ 7:1 - 13:44
example.poi @ 2:1 - 13:44
example.poi @ 1:1 - 13:44
```
After:
```
Error: 'true' is not a constructor of {none, some value}.
example.poi @ 2:12 - 5:1
example.poi @ 10:31 - 10:39 …
```

Hide frames corresponding to Binding expressions from stack traces

---

src/compiler.cpp
src/error.cpp
src/interpreter.cpp
src/parser.cpp
src/tokenizer.cpp
src/value.cpp

Make sure all global definitions except those in main.cpp are in the `Poi` namespace. Now we can be confident that Poi will be able to link against any other code without naming conflicts.
**Fixes:** N/A

Make sure all global definitions except those in main.cpp are in the `Poi` namespace

---

cli/main.cpp
include/ast.h
include/bytecode.h
include/compiler.h
include/interpreter.h
include/ir.h
src/ast.cpp
src/bytecode.cpp
src/compiler.cpp
src/interpreter.cpp
src/ir.cpp

Add stack traces. Note that tail recursion optimization means many stack frames are omitted in general.
Given this example:
```
f = x -> (a -> a) (a = a, a)
g = x -> (a -> a) (f (a -> a))
h = x -> (a -> a) (g (a -> a))
h (a -> a)
```
We get the following error:
```
Error: Recursive reference evaluated before the knot has been tied.
Stack trace:
example.poi @ 1:24
example.poi @ 2:19 - 2:30
example.poi @ 3:19 - 3:30
example.poi @ 4:1 - 4:10
Location: example.poi @ 1:24
f = x -> (a -> a) (a = a, a)
^
```
**Fixes:** N/A

Add stack traces

---

include/bytecode.h
include/ir.h
src/ast.cpp
src/bytecode.cpp
src/interpreter.cpp
src/ir.cpp

Rename some instructions:
- `CALL_NON_TAIL` -> `CALL`
- `CALL_TAIL` -> `TAIL_CALL`
- `COPY` -> `MOVE`
**Fixes:** N/A

Rename some instructions

---

cli/main.cpp
include/bytecode.h
include/ir.h
include/optimizer.h
src/ast.cpp
src/bytecode.cpp
src/compiler.cpp
src/interpreter.cpp
src/ir.cpp
src/optimizer.cpp
src/value.cpp
tests/application.json
tests/binding.json
tests/comment.json
tests/group.json
tests/id.json
tests/line_continuation.json
tests/unicode.json

Implement an optimal linear-time register allocator based on linear scanning. This is possible because we have an unbounded number of registers available.
Consider the following benchmark program:
```
zero = f -> x -> x
succ = n -> f -> x -> f (n f x)
add = m -> n -> f -> x -> m f (n f x)
mul = m -> n -> f -> m (n f)
exp = m -> n -> n m
one = succ zero
two = add one one
four = mul two two
six = add four two
sixteen = mul four four
big = exp sixteen six
big (x -> x) (x -> x)
```
Without the register allocator, this takes ~11.960 seconds on my laptop. With the register allocator, it takes ~9.962 seconds. That's a **16.7%** speedup.
```
0 BEGIN_FIXPOINT destination=1
1 CREATE_FUNCTION destination=2 body=74 frame_size=2 captures=[]
2 END_FIXPOINT fixpoint=1 target=2
3 BEGIN_FIXPOINT …
```

Implement a register allocator
